"""
Abulla_Guidance — minimal, environment-free policy wrapper for relative guidance.

Target use-case
---------------
You provide **measured relative pose** (position + orientation) each call (e.g., from
OptiTrack). The class builds the two 6-D observations expected by Abdulla's
policies (translation and attitude), queries the two TD3 actors loaded from disk,
and returns both the **normalized actions** (in [-1, 1]) and **scaled commands**
(linear/ angular accelerations).

Designed for stable_baselines3==1.1.0 and Torch 1.12.x.

Inputs expected per call
------------------------
- pos: np.ndarray shape (3,) — relative position [x, y, z] (meters)
- quat: iterable of 4 — quaternion. "xyzw".
- timestamp (float, optional): seconds. If omitted, dt_fallback is used for rate estimation.
- dt (float, optional): directly supply the time delta since the previous call (seconds).

Outputs per call
----------------
A dict with:
- 'action_norm': concatenated 6-D normalized action in [-1, 1] (3 translational, 3 rotational)
- 'command': { 'lin_accel': (3,), 'ang_accel': (3,) } scaled by max_* gains (optionally time-scaled)
- 'dt_used': dt actually used for rate estimation
- 'obs': the-D observation pieces used by the policies

Notes - these were generated by chatGBT 
-----
- This reproduces the original state split the policies were trained on:
  obsR = [pos_biased, vel]
  obsA = [euler_err, ang_rate]
  where pos_biased = pos + [0, 0, pos_z_bias].
- No environment, no PANGU/vision calls, no noise added.
- Quaternion is normalized internally; Euler sequence defaults to 'xyz'.
- The max command magnitudes mirror the original minimal example:
  max_control_lin = 0.01 (≈ m/s²), max_control_ang = pi/72 (≈ 2.5°/s²).
  consumer expects per-step delta_velocity/delta_omega instead of accelerations.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Tuple, Dict, Any
import numpy as np
from scipy.spatial.transform import Rotation as R
from scipy.integrate import solve_ivp
import os

# SB3 v1.1.0
from stable_baselines3 import TD3


@dataclass ## like c++ struct 
class GuidanceConfig:

    ## get the script directory as the weights are here
    script_dir:str = os.path.dirname(os.path.abspath(__file__))

    # Paths to the two actor checkpoints trained for: translation and attitude
    modelR_path: str = script_dir + "/TD3_Ren_Working_X20_high_1 1"
    modelA_path: str = script_dir + "/TD3_Att_Working_X1_high 1"

    # Observation construction
    pos_z_bias: float = 0.25            # meters (matches abdulla's script)

    # Action scaling (pre‑integration command magnitudes)
    max_control_lin: float = 1.0e-2     # ≈ m/s²
    max_control_ang: float = np.pi/72   # ≈ rad/s² (~2.5°/s²)

    # Fixed-step integration - as described by abdulla 
    sample_t: float = 1.0               # seconds per policy/update step
    dtime: float = 0.01                 # seconds per physics substep

    # Rate estimation
    dt_fallback: float = 1.0            # seconds, used if no timestamps provided


class Abulla_Guidance:
    """Environment-free guidance wrapper around two TD3 policies (for max's use)

    Typical usage:
        g = Abulla_Guidance()
        out = g(pos=[0.1, 0.0, 20.0], quat=[0,0,0,1], timestamp=0.0)
        # later...
        out = g(pos=[0.099, 0.0, 19.99], quat=[0,0,0,1], timestamp=1.0)
    """

    def __init__(self, config: GuidanceConfig | None = None, device: str = "auto") -> None:
        self.cfg = config or GuidanceConfig()

        # Load policies (SB3 v1.1.0)
        self.modelR: TD3 = TD3.load(self.cfg.modelR_path, device=device)
        self.modelA: TD3 = TD3.load(self.cfg.modelA_path, device=device)

        # Internal state for finite‑difference rates
        self._prev_pos: Optional[np.ndarray] = None
        self._prev_euler_err: Optional[np.ndarray] = None
        self._prev_time: Optional[float] = None



    # Public API: call with relative pose -> returns action dict
    def __call__(
        self,
        pos: np.ndarray | Tuple[float, float, float],
        quat: Optional[Tuple[float, float, float, float]], ## quat is scaler last (xyzw)
        timestamp: Optional[float] = None,
        dt: Optional[float] = None, ## for later to apply actual dt
    ) -> Dict[str, Any]:
        
        pos = np.asarray(pos, dtype=np.float32).reshape(3)

        # Normalize quaternion to be safe
        n = np.linalg.norm(quat)
        if n == 0:
            quat = np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float64)
        else:
            quat = quat / n
        quat = np.asarray(quat, dtype=np.float64).reshape(4)

        # pos, quat = self.correct_pose_for_guidance(pos, quat)
        
        euler = R.from_quat(quat).as_euler("xyz", degrees=False).astype(np.float32)

        # Angle error is just the Euler vector in the chosen sequence (target frame ~ identity)
        euler_err = self._wrap_angles(euler.astype(np.float32))

        # Compute dt for rates - currently fixed 
        dt_used = self.cfg.sample_t 

        # Finite‑difference linear and angular rates
        if self._prev_pos is None:
            vel = np.zeros(3, dtype=np.float32)
            ang_rate = np.zeros(3, dtype=np.float32)
        else:
            vel = (pos - self._prev_pos) / dt_used
            d_ang = self._wrap_angles(euler_err - self._prev_euler_err)
            ang_rate = d_ang / max(dt_used, 1e-6)

        # Observation split the actors expect
        obsR = np.concatenate([pos.astype(np.float32), vel.astype(np.float32)], axis=0).reshape(1, 6)
        obsA = np.concatenate([euler_err.astype(np.float32), ang_rate.astype(np.float32)], axis=0).reshape(1, 6)

        # Actor predictions (normalized actions in [-1, 1])
        aR = self.modelR.predict(obsR)
        aA = self.modelA.predict(obsA)
        aR = np.asarray(aR[0], dtype=np.float32).reshape(3)
        aA = np.asarray(aA[0], dtype=np.float32).reshape(3)

        # Scale to physical command magnitudes (accelerations by default)
        lin_cmd = aR * self.cfg.max_control_lin
        ang_cmd = aA * self.cfg.max_control_ang

        lin_cmd = lin_cmd * dt_used
        ang_cmd = ang_cmd * dt_used

        # Update memory for next call
        self._prev_pos = pos.copy()
        self._prev_euler_err = euler_err.copy()
        # self._prev_time = (self._prev_time + dt_used) if (self._prev_time is not None) else timestamp

        # Predict next pose using same substepped integration
        next_pose = None
        next_twist = None

        substeps = max(1, int(round(self.cfg.sample_t / self.cfg.dtime))) ## should be 100Hz
        dt_sub = self.cfg.dtime

        # Gains per substep (dv and dw magnitudes)
        dv_step_gain = 0.01 * dt_sub          # matches env: max_control_vel = 0.01 * dtime
        dw_step_gain = (np.pi / 72) * dt_sub  # matches env: max_control_dw = (pi/72) * dtime

        pos_i = pos.astype(np.float64).copy()
        vel_i = vel.astype(np.float64).copy()
        ang_i = ang_rate.astype(np.float64).copy()
        q_i = quat.copy()

        for _ in range(substeps):
            # Linear (semi-implicit Euler): v <- v + Δv ; p <- p + v*dt
            vel_i = vel_i + (aR.astype(np.float64) * dv_step_gain)
            pos_i = pos_i + vel_i * dt_sub

            ang_i = ang_i + (aA.astype(np.float64) * dw_step_gain)  # ω_k+1
            sol = solve_ivp(_qdot_xyzw, (0.0, dt_sub), q_i, t_eval=(dt_sub,), max_step=dt_sub, args=(ang_i,))
            q_i = sol.y[:, -1]

        ## normalise q
        q_i = q_i / np.linalg.norm(q_i)

        next_pose = {"pos": pos_i.astype(np.float32), "quat_xyzw": q_i.astype(np.float32)}
        next_twist = {"vel": vel_i.astype(np.float32), "ang_rate": ang_i.astype(np.float32)}

        return {
            "action_norm": np.concatenate([aR, aA], axis=0),
            "command": {
                "lin_accel": lin_cmd,
                "ang_accel": ang_cmd,
                # Per-substep increments used by the predictor (mirror of env)
                "lin_dv_per_substep": aR * dv_step_gain,
                "ang_dw_per_substep": aA * dw_step_gain,
            },
            "dt_used": dt_used,
            "obs": {
                "pos": pos,
                "vel": vel,
                "euler_err": euler_err,
                "ang_rate": ang_rate,
            },
            "next_pose": next_pose,
            "next_twist": next_twist,
        }
    

    # Optional convenience to clear internal state
    def reset(self) -> None:
        self._prev_pos = None
        self._prev_euler_err = None
        self._prev_time = None

    # --- helpers ---
    def _resolve_dt(self, timestamp: Optional[float], dt: Optional[float]) -> float:
        if dt is not None:
            return float(dt)
        if timestamp is None:
            return float(self.cfg.dt_fallback)
        if self._prev_time is None:
            self._prev_time = float(timestamp)
            return float(self.cfg.dt_fallback)
        d = float(timestamp - self._prev_time)
        # Guard against non‑monotonic clocks
        return float(d if d > 0 else self.cfg.dt_fallback)

    @staticmethod
    def _wrap_angles(a: np.ndarray) -> np.ndarray:
        # Map angles to (−pi, pi]
        return ((a + np.pi) % (2 * np.pi)) - np.pi
    
# Define once (module-level or above __call__)
def _skew_w4(w):
    wx, wy, wz = w
    return np.array([
        [ 0.0,  -wx,  -wy,  -wz],
        [  wx,  0.0,   wz,  -wy],
        [  wy,  -wz,  0.0,   wx],
        [  wz,   wy,  -wx,  0.0],
    ], dtype=np.float64)

def _qdot_xyzw(t, q, w):
    # dq/dt = 0.5 * skew(w) * q  (xyzw ordering)
    return 0.5 * _skew_w4(w).dot(q)



if __name__ == "__main__":
    # Tiny demo with identity orientation and synthetic motion
    g = Abulla_Guidance()
    t = 0.0
    pos = np.array([0.10, 0.05, 20.0], dtype=np.float32)
    quat_xyzw = np.array([0.0, 0.0, 0.0, 1.0])

    for k in range(5):
        out = g(pos=pos, quat=quat_xyzw)
        print(f"step={k} next_rel_pos={out['next_pose']['pos']}")
        # Pretend the robot moved a bit toward the target
        pos = out["next_pose"]["pos"]
